name: my_env
channels:
  - defaults
  - conda-forge
  - pytorch
  
dependencies:
  - python=3.11
  - pip
  - pytorch==2.6.0
  - numpy==2.2.3
  - pip:
      - tiktoken==0.9.0
      - datasets==3.3.2
      - tqdm==4.67.1