name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install build pytest
    - name: Build package
      run: |
        python3 -m build
    - name: Install package
      run: |
        pip install dist/*.whl
    - name: Run Tests
      run: |
        pytest --doctest-modules --junitxml=report.xml
