name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pytest
    #     pip install -r requirements.txt
    - name: Build package
      run: |
        pip install setuptools wheel
        python3 setup.py sdist bdist_wheel
    - name: Install package
      run: |
        pip install dist/*.whl
    # - name: Run Tests
    #   run: |
    #     pytest --doctest-modules --junitxml=report.xml